"""add missing columns

Revision ID: 5ea0dbabb9f6
Revises: 20250506_0001
Create Date: 2026-06-23 20:26:00.224839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea0dbabb9f6'
down_revision = '20250506_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('dominant_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'dominant_color')
    # ### end Alembic commands ###
